version: '3.7'

volumes:
  redis_data:
  redisinsight_data:

services:
  redis:
    image: 'redis:6.0.6'
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
      - ./app/redis_client/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  redisinsight:
    image: 'redislabs/redisinsight:latest'
    ports:
      - '8001:8001'
    volumes:
      - ./redisinsight_data:/db

  fastapi_app:
    build: .
    # image: 'football-prediction:latest'  # Replace with the actual image and tag for your FastAPI application
    # command: "python -m debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload"\
    command: "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - '8000:8000'
      - '5678:5678'
    volumes:
      - "./:/app"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379